# Generated by Django 5.2.17 on 2026-08-30 03:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('is_hod', models.BooleanField(default=False)),
                ('is_head_approver', models.BooleanField(default=False)),
                ('is_procurement_officer', models.BooleanField(default=False)),
                ('is_storekeeper', models.BooleanField(default=False)),
                ('is_stock_manager', models.BooleanField(default=False)),
                ('is_asset_manager', models.BooleanField(default=False)),
                ('can_access_tickets', models.BooleanField(default=False)),
                ('is_gatekeeper', models.BooleanField(default=False)),
                ('is_ticket_viewer', models.BooleanField(default=False)),
                ('osh_role', models.CharField(blank=True, choices=[('', 'No OSH Role'), ('admin', 'OSH Admin'), ('manager', 'HSE Manager'), ('officer', 'HSE Officer'), ('auditor', 'Auditor'), ('employee', 'Employee'), ('viewer', 'Read-Only Viewer')], default='', help_text='Role within the OSH / EHS compliance module.', max_length=20, verbose_name='OSH Role')),
            ],
            options={
                'permissions': [('can_create_po', 'Can create purchase order'), ('can_approve_hod', 'Can approve as HOD'), ('can_approve_final', 'Can give final head approval')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
