# Generated by Django 5.2.17 on 2026-08-30 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('audit_type', models.CharField(choices=[('INTERNAL', 'Internal Audit'), ('EXTERNAL', 'External Audit'), ('REGULATORY', 'Regulatory / Government'), ('CERT', 'Certification Audit'), ('SURV', 'Surveillance Audit')], default='INTERNAL', max_length=20)),
                ('auditor', models.CharField(blank=True, max_length=255)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('PASS', 'Pass / No Major Findings'), ('CONDITIONAL', 'Conditional Pass'), ('FAIL', 'Fail / Major Findings')], max_length=20)),
                ('scope', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='audit_reports/')),
                ('findings_count', models.PositiveIntegerField(default=0)),
                ('major_nc_count', models.PositiveIntegerField(default=0)),
                ('minor_nc_count', models.PositiveIntegerField(default=0)),
                ('observations_count', models.PositiveIntegerField(default=0)),
                ('next_audit_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
