# Generated by Django 5.2.17 on 2026-08-30 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('supplier_contact', models.CharField(blank=True, max_length=255)),
                ('supplier_email', models.EmailField(blank=True, max_length=254)),
                ('order_reference', models.CharField(blank=True, max_length=100)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ORDERED', 'Ordered — Sent to Stores')], default='OPEN', max_length=20)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_orders_placed', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_order', to='purchase_orders.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('po_line_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_line', to='purchase_orders.polineitem')),
                ('procurement_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proc_line_items', to='procurement.procurementorder')),
            ],
        ),
    ]
