# Generated by Django 5.2.17 on 2026-08-30 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=50)),
                ('sourcing', models.CharField(blank=True, choices=[('LOCAL', 'Local'), ('IMPORT', 'Import')], default='', max_length=10)),
                ('stock_required', models.BooleanField(default=True)),
                ('purchase_pattern', models.CharField(blank=True, default='ONGOING', max_length=10)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('lead_time_months', models.DecimalField(decimal_places=1, default=3, max_digits=4)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('open_order', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('usage_jun', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('usage_jul', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('usage_aug', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('usage_sep', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('usage_oct', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('usage_nov', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('usage_dec', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('usage_jan', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('usage_feb', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('usage_mar', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('usage_apr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('usage_may', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('to_order', models.BooleanField(default=False)),
                ('order_qty', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['qb_code'],
            },
        ),
        migrations.CreateModel(
            name='StockUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_created', models.IntegerField(default=0)),
                ('rows_updated', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
