# Generated by Django 5.2.17 on 2026-08-30 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('departments', '0001_initial'),
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('license_type', models.CharField(choices=[('BUSINESS', 'Business License'), ('EQUIPMENT', 'Equipment Certificate'), ('FIRE', 'Fire Certificate'), ('EMPLOYEE', 'Employee Certificate/License'), ('ENVIRONMENTAL', 'Environmental Permit'), ('INSURANCE', 'Insurance Policy'), ('OPERATIONAL', 'Operational Permit'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('issuing_authority', models.CharField(blank=True, max_length=200)),
                ('holder', models.CharField(blank=True, help_text='Person/entity holding this license', max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('renewal_lead_days', models.PositiveIntegerField(default=30, help_text='Alert this many days before expiry')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='licenses/')),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('EXPIRING', 'Expiring Soon'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending Renewal')], default='VALID', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='equipment.equipment')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses_responsible', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expiry_date', 'title'],
            },
        ),
    ]
