# Generated by Django 5.2.17 on 2026-08-30 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('hazard_source', models.CharField(blank=True, max_length=200)),
                ('likelihood', models.IntegerField(choices=[(1, '1 — Rare'), (2, '2 — Unlikely'), (3, '3 — Possible'), (4, '4 — Likely'), (5, '5 — Almost Certain')], default=3)),
                ('impact', models.IntegerField(choices=[(1, '1 — Negligible'), (2, '2 — Minor'), (3, '3 — Moderate'), (4, '4 — Major'), (5, '5 — Catastrophic')], default=3)),
                ('likelihood_residual', models.IntegerField(blank=True, choices=[(1, '1 — Rare'), (2, '2 — Unlikely'), (3, '3 — Possible'), (4, '4 — Likely'), (5, '5 — Almost Certain')], null=True)),
                ('impact_residual', models.IntegerField(blank=True, choices=[(1, '1 — Negligible'), (2, '2 — Minor'), (3, '3 — Moderate'), (4, '4 — Major'), (5, '5 — Catastrophic')], null=True)),
                ('controls', models.TextField(blank=True, help_text='Existing controls')),
                ('mitigation_plan', models.TextField(blank=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MITIGATED', 'Mitigated'), ('ACCEPTED', 'Accepted'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_owned', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
