# Generated by Django 5.2.17 on 2026-08-30 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chemical_name', models.CharField(max_length=255)),
                ('cas_number', models.CharField(blank=True, help_text='CAS Registry Number', max_length=20)),
                ('product_code', models.CharField(blank=True, max_length=50)),
                ('hazard_class', models.CharField(choices=[('FLAMMABLE', 'Flammable'), ('CORROSIVE', 'Corrosive'), ('TOXIC', 'Toxic'), ('EXPLOSIVE', 'Explosive'), ('OXIDISER', 'Oxidiser'), ('IRRITANT', 'Irritant'), ('ENVIRONMENTAL', 'Environmental Hazard'), ('NONE', 'Non-Hazardous')], default='NONE', max_length=20)),
                ('hazard_description', models.TextField(blank=True)),
                ('storage_location', models.CharField(blank=True, max_length=255)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, help_text='e.g. L, kg', max_length=20)),
                ('minimum_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('sds_file', models.FileField(blank=True, null=True, upload_to='sds/', verbose_name='SDS/MSDS File')),
                ('sds_date', models.DateField(blank=True, null=True, verbose_name='SDS Issue Date')),
                ('required_ppe', models.TextField(blank=True, help_text='PPE required when handling')),
                ('handling_requirements', models.TextField(blank=True)),
                ('storage_requirements', models.TextField(blank=True)),
                ('disposal_method', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['chemical_name'],
            },
        ),
    ]
