# Generated by Django 5.2.17 on 2026-08-30 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('provider', models.CharField(choices=[('twilio', 'Twilio'), ('meta', 'Meta Cloud API'), ('custom', 'Custom REST')], default='twilio', max_length=20)),
                ('account_sid', models.CharField(blank=True, help_text='Twilio Account SID or Meta WABA ID', max_length=200)),
                ('auth_token', models.CharField(blank=True, help_text='Twilio Auth Token or Meta API Token', max_length=200)),
                ('from_number', models.CharField(blank=True, help_text='WhatsApp sender number e.g. +12345678900', max_length=30)),
                ('api_url', models.CharField(blank=True, help_text='Custom REST endpoint URL', max_length=500)),
                ('api_key', models.CharField(blank=True, max_length=300)),
                ('extra_headers', models.TextField(blank=True, help_text='JSON dict of extra headers for custom provider')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
            },
        ),
        migrations.CreateModel(
            name='VisitorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('visitor_name', models.CharField(max_length=255)),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('visitor_phone', models.CharField(blank=True, help_text='WhatsApp-capable number e.g. +254712345678', max_length=30)),
                ('visitor_company', models.CharField(blank=True, max_length=255)),
                ('visitor_id_number', models.CharField(blank=True, help_text='National ID / Passport number', max_length=100)),
                ('scheduled_date', models.DateField()),
                ('scheduled_start', models.TimeField()),
                ('scheduled_end', models.TimeField(blank=True, help_text='Expected end time (optional).', null=True)),
                ('agenda', models.TextField(blank=True, help_text='Purpose of visit / meeting agenda (optional).')),
                ('vehicle_plate', models.CharField(blank=True, help_text='e.g. KCA 001A', max_length=50)),
                ('vehicle_make', models.CharField(blank=True, help_text='e.g. Toyota Prado', max_length=100)),
                ('vehicle_colour', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ARRIVED', 'Arrived'), ('IN_MEETING', 'In Meeting'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('badge_number', models.CharField(blank=True, max_length=20)),
                ('host_notified_at', models.DateTimeField(blank=True, null=True)),
                ('arrival_whatsapp_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(blank=True, help_text='User who created this appointment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_made', to=settings.AUTH_USER_MODEL)),
                ('host_department', models.ForeignKey(blank=True, help_text='Department being visited (used if host user is not in system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_appointments', to='departments.department')),
                ('host_user', models.ForeignKey(blank=True, help_text='Staff member being visited. Leave blank if unknown — department HOD will be notified.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='visitors.visitorappointment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
