# Generated by Django 5.2.17 on 2026-08-30 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('WASTE', 'Waste Management'), ('WATER', 'Water Usage'), ('ENERGY', 'Energy Consumption'), ('EMISSIONS', 'Air Emissions'), ('CHEMICAL', 'Chemical Handling'), ('NOISE', 'Noise'), ('LAND', 'Land Contamination'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('activity', models.CharField(blank=True, max_length=255)),
                ('significance', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('legal_requirement', models.TextField(blank=True)),
                ('current_controls', models.TextField(blank=True)),
                ('target_value', models.CharField(blank=True, max_length=100)),
                ('actual_value', models.CharField(blank=True, max_length=100)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50)),
                ('monitoring_frequency', models.CharField(blank=True, max_length=100)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='env_aspects', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
