# Generated by Django 5.2.17 on 2026-08-30 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('company_reg', models.CharField(blank=True, max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('services_provided', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending Review'), ('SUSPENDED', 'Suspended'), ('BLACKLISTED', 'Blacklisted')], default='PENDING', max_length=20)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('has_insurance', models.BooleanField(default=False)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('has_safety_policy', models.BooleanField(default=False)),
                ('has_method_statement', models.BooleanField(default=False)),
                ('has_risk_assessment', models.BooleanField(default=False)),
                ('has_training_records', models.BooleanField(default=False)),
                ('has_valid_license', models.BooleanField(default=False)),
                ('compliance_score', models.PositiveIntegerField(default=0, help_text='0-100 compliance score')),
                ('last_assessment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractors_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
