# Generated by Django 5.2.17 on 2026-08-30 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('incident_type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('NEAR_MISS', 'Near Miss'), ('INJURY', 'Injury / Illness'), ('ENVIRONMENTAL', 'Environmental Incident'), ('EQUIPMENT', 'Equipment Incident'), ('SECURITY', 'Security Incident'), ('FIRE', 'Fire / Explosion'), ('SPILLAGE', 'Chemical Spillage'), ('OTHER', 'Other')], default='ACCIDENT', max_length=20)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical / Fatality'), ('MAJOR', 'Major'), ('MODERATE', 'Moderate'), ('MINOR', 'Minor'), ('NEGLIGIBLE', 'Negligible / Near Miss')], default='MINOR', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('incident_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('persons_involved', models.TextField(blank=True, help_text='Names of persons involved')),
                ('witnesses', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('immediate_action', models.TextField(blank=True, help_text='Immediate actions taken')),
                ('root_cause', models.TextField(blank=True)),
                ('contributing_factors', models.TextField(blank=True)),
                ('investigation_notes', models.TextField(blank=True)),
                ('injuries_description', models.TextField(blank=True)),
                ('lost_time_days', models.PositiveIntegerField(default=0)),
                ('property_damage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('regulatory_notification_required', models.BooleanField(default=False)),
                ('regulatory_notified', models.BooleanField(default=False)),
                ('regulatory_ref', models.CharField(blank=True, max_length=100)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_reported', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-incident_date'],
            },
        ),
    ]
