# Generated by Django 5.2.17 on 2026-08-30 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('po_submitted', 'PO Submitted'), ('po_approved', 'PO Approved'), ('po_rejected', 'PO Rejected'), ('po_ordered', 'PO Ordered'), ('po_deadline', 'PO Deadline'), ('ticket_update', 'Ticket Update'), ('ticket_overdue', 'Ticket Overdue'), ('grn_created', 'GRN Created'), ('asset_update', 'Asset Update'), ('visitor', 'Visitor Alert'), ('expiry', 'Certificate/PPE Expiring'), ('inspect', 'Inspection Due'), ('maint', 'Maintenance Due'), ('training', 'Training Expiring'), ('overdue', 'Overdue Action'), ('incident', 'New Incident'), ('finding', 'New Finding'), ('general', 'General')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
